-- SBA Description Updates — 2026-03-16 00:16
-- 72 venues updated, 28 skipped

UPDATE venues SET description = 'Established brewery in the historic gold rush town of Beechworth, producing a diverse range of craft beers including pale ales, IPAs, and alcohol-free options. The venue offers tastings and hosts events throughout the year.' WHERE slug = 'beechworth-brewing';
UPDATE venues SET description = 'Iconic Coonawarra winery specialising in world-class Cabernet Sauvignon from terra rossa soils, with a modern cellar door housed in a historic limestone building offering tastings and specialty beverages.' WHERE slug = 'parker-coonawarra';
UPDATE venues SET description = 'Award-winning craft brewery in Burswood featuring house-brewed beers and a gastrobrewery combining innovative brewing with gourmet food including burgers and seafood.' WHERE slug = 'blasta-brewing';
UPDATE venues SET description = 'An independent micro-brewery at The Marina in Mindarie crafting award-winning beers since 2005, with rotating small batch releases every eight to ten weeks. Stunning ocean views, locally sourced grill menu, and pizzas complement the core and specialty brews.' WHERE slug = 'indian-ocean-brewing';
UPDATE venues SET description = 'Secluded Margaret River vineyard nestled in jarrah forest, offering wine tastings, accommodation in spa chalets, and a focus on terroir-driven winemaking that captures the region''s character.' WHERE slug = 'brookland-valley';
UPDATE venues SET description = 'Foreigner Brewing is a Brunswick brewery specializing in traditional Czech Pilsner developed with a Czech master brewer, alongside rotating sours, pale ales, and dark lagers. The intimate warehouse venue fosters community connection with brewers often behind the bar, and offers pool, darts, and board games.' WHERE slug = 'foreigner-brewing';
UPDATE venues SET description = 'An independent Melbourne brewery and taproom in Reservoir offering a rotating selection of craft beers alongside branded merchandise. Known for creative seasonal releases and mixed pack options for beer exploration.' WHERE slug = 'hawkers-reservoir';
UPDATE venues SET description = 'Based on the website content provided, I cannot write an accurate description for Rocks Brewing Melbourne. The website content appears to be for Rocky Ridge brewery in Western Australia (with locations in Burswood, Brunswick, Busselton, Duncraig, and Jindong), not a Melbourne outpost. There is no information confirming a Melbourne location or venue details for Rocks Brewing Melbourne.

I recommend verifying the correct website or providing content specific to the Melbourne venue before I write the description.' WHERE slug = 'rocks-brewing-melb';
UPDATE venues SET description = 'Located in The Cannery, Rosebery, this French-inspired brewpub pairs award-winning house-made beers and cocktails with seasonal, locally-sourced cuisine. The brewery director crafts beverages that complement the chef''s produce-driven dishes, with new varieties released monthly.' WHERE slug = 'frenchies-brewery';
UPDATE venues SET description = 'Australia''s first cooperative brewery, democratically run and member-owned, offering craft beers and the opportunity to become a shareholder with voting rights on brewing decisions and access to tastings and brew days.' WHERE slug = 'hopsters-brewing';
UPDATE venues SET description = 'Boutique Hunter Valley winery housed in a renovated church, offering contemporary wines paired with premium salumi and cheese at the cellar door. Known for distinctive, thought-provoking styles that blend traditional and modern winemaking approaches.' WHERE slug = 'usher-tinkler';
UPDATE venues SET description = 'Small-batch brewery in Forrest producing preservative-free, vegan-friendly beers with locally grown hops and pure Otways water. On-site brewing visible from the bar and dining hall, which serves modern Australian cuisine paired with their beers.' WHERE slug = 'forrest-brewing';
UPDATE venues SET description = 'Located in East Perth, this brewery and kitchen offers fresh pints straight from the source alongside a food menu. Known for bold, distinctive beers and a vibrant taproom atmosphere, Bright Tank also hosts events and functions.' WHERE slug = 'bright-tank-brewing';
UPDATE venues SET description = 'Founded in 1992, this Margaret River winery features sweeping views over the Five Ashes vineyard and Rusty Creek valley, framed by native Karri trees. The on-site restaurant serves seasonal lunch daily, while the cellar door showcases their range of white and red wines.' WHERE slug = 'hamelin-bay';
UPDATE venues SET description = 'Biodynamic Margaret River winery producing single-vineyard wines with minimal intervention. The welcoming cellar door offers guided tastings and seasonal food pairings, open daily from 10:30am to 4:30pm.' WHERE slug = 'mchenry-hohnen';
UPDATE venues SET description = 'Located at 68 Chambers Road in Hay Valley, this Adelaide Hills brewery invites visitors to enjoy craft brews amid scenic surroundings. The venue offers long lunch bookings and brewery tours at their main location, operating Wednesday to Friday 11am-5pm and weekends 11am-5pm.' WHERE slug = 'mismatch-hills';
UPDATE venues SET description = 'Located at 168 Olivers Road, Swell Brewing Co is a McLaren Vale brewery and taphouse open daily, serving craft beers including Hazy IPAs, West Coast IPAs, and kettle sours. The venue welcomes visitors to enjoy food and drinks on-site while offering online ordering and beer club membership.' WHERE slug = 'swell-brewing';
UPDATE venues SET description = 'Single estate winery specialising in Italian and emerging varieties including Fiano, Manseng, and Tempranillo, alongside wines from 70-year-old Shiraz vines. Offers curated tastings in a beautiful cellar door setting, with hands-on education from the owner about their distinctive wines.' WHERE slug = 'savina-lane';
UPDATE venues SET description = 'Award-winning Brisbane brewery with two venues offering hop-forward craft beers and modern Australian cuisine. The Yeerongpilly location serves as their spiritual home, while their Sunshine Coast Social House provides a relaxed dining atmosphere.' WHERE slug = 'slipstream-brewing';
UPDATE venues SET description = 'Salisbury-based brewery crafting bold, flavourful beers across ales, lagers, stouts and sours, including experimental wild beers through their Bunker range. The taproom offers limited opening hours with a focus on quality over quantity.' WHERE slug = 'ballistic-beer';
UPDATE venues SET description = 'Located in Woolloongabba, this Brisbane brewery and kitchen produces craft beer and offers a venue to enjoy their brews on-site. Good Land Brewing Co regularly releases new beer batches and welcomes visitors to experience their offering.' WHERE slug = 'good-land-brewing';
UPDATE venues SET description = 'Established in 1997 in the Heathcote region, this small winery produces hand-tended, estate-grown reds from unirrigated vines on granitic soil. Visitors can taste wines amongst the barrels at the cellar door, experiencing fruit-driven wines reflective of the region''s terroir.' WHERE slug = 'coliban-valley';
UPDATE venues SET description = 'Heathcote''s longest-established winery, founded in 1955 and now run by third-generation winemaker Simon Osicka. Hand-tended mature vines on sandy loam produce intensely flavoured reds, all estate-grown, made and bottled on-site.' WHERE slug = 'paul-osicka';
UPDATE venues SET description = 'Six-generation family winery in Rutherglen producing Durif, Shiraz, Muscat and other varieties from estate vineyards since 1860. On-site restaurant showcases local ingredients and French-influenced cuisine.' WHERE slug = 'jones-winery-rutherglen';
UPDATE venues SET description = 'Award-winning single-estate cool climate winery in Gippsland with cellar door, restaurant serving modern Australian cuisine, and French-inspired wines hand-picked and made on-site by the family owners.' WHERE slug = 'cannibal-creek';
UPDATE venues SET description = 'Wild ale and sour specialist operating a joint taproom with Mountain Culture Beer Co in Marrickville. Located on Brompton Street near The Factory Theatre and local cafes, Village offers a relaxed atmosphere with snacky, shareable food and carefully curated beer selections.' WHERE slug = 'wildflower-brewing';
UPDATE venues SET description = 'Family-owned winery producing premium wines from Margaret River and Great Southern regions. The 5-star rated cellar door features the striking Wine Chapel, offering curated tastings of méthage traditionnelle sparkling wines paired with local charcuterie.' WHERE slug = 'howard-park';
UPDATE venues SET description = 'Historic Clarendon vineyard first planted in 1971, now producing wines under its own label since 2012. Situated on high elevation hills in McLaren Vale, the property is farmed using organic and biodynamic practices and offers tastings of their distinctive Brooks Road Shiraz and other block series wines.' WHERE slug = 'hickinbotham-clarendon';
UPDATE venues SET description = 'Founded by Master Distiller Cameron Syme in 2004, this Albany distillery produces premium craft spirits including Limeburners Single Malt Whisky, Giniversity Gin, Tiger Snake and Dugite Whiskeys. Visitors can tour the facility and participate in gin blending classes.' WHERE slug = 'great-southern-distilling';
UPDATE venues SET description = 'Located in Swan Valley, this distillery and kitchen combines hand-crafted spirits with hyper-local West Australian cuisine featuring native ingredients, set in a rustic space that pairs expertly produced gin with thoughtfully sourced dishes.' WHERE slug = 'old-youngs';
UPDATE venues SET description = 'Celebrated Barossa Valley shiraz specialist known for distinctive single-vineyard expressions including the flagship Roennfeldt Road range. Offers tastings and direct online sales with free national shipping on orders above $400.' WHERE slug = 'greenock-creek';
UPDATE venues SET description = 'Tanunda winery producing distinctive single vineyard and single barrel Shiraz, Grenache, Mataro and GSM blends. Cellar door tastings available at Artisans of Barossa, with private appointments by arrangement.' WHERE slug = 'schwarz-wine';
UPDATE venues SET description = 'Cult Barossa shiraz producer offering tastings by appointment, showcasing single-vineyard expressions from premium sites including Hongell, Laycock, Roennfeldt Road and Stonegarden across the region.' WHERE slug = 'standish-wine';
UPDATE venues SET description = 'Located in Murrumbateman, Shaw Vineyard Estate offers award-winning cool climate wines and seated tasting experiences overlooking the Southern Tablelands. The estate features a cellar door, restaurant, and multiple event spaces set within picturesque regional landscapes.' WHERE slug = 'shaw-vineyard';
UPDATE venues SET description = 'Perched at 900+ metres in New England''s state forest, this family-owned winery specialises in small-batch, single-vineyard wines including rare varietals like Tempranillo Blanc. The cellar door offers panoramic Macintyre Valley views and curated tasting experiences showcasing cool-climate expressions.' WHERE slug = 'toppers-mountain';
UPDATE venues SET description = 'Nestled in the picturesque Huon Valley south of Hobart, this award-winning winery specialises in Pinot Noir and offers cellar door tastings, an on-site restaurant, and scenic vineyard views alongside pastoral landscapes.' WHERE slug = 'home-hill';
UPDATE venues SET description = 'Sixth-generation family winery in the Derwent Valley producing biodynamic sparkling and Pinot Noir using minimal intervention and no synthetic inputs. Visitors can experience tastings at the cellar door on Rowbottoms Road in Granton.' WHERE slug = 'stefano-lubiana';
UPDATE venues SET description = 'One of the Mornington Peninsula''s longest-running family wineries, Stumpy Gully offers estate-grown wines at its cellar door alongside an Asian fusion restaurant. Set among sprawling vines and gardens just 50 minutes from Melbourne, it provides seated tastings and a scenic dining experience.' WHERE slug = 'stumpy-gully';
UPDATE venues SET description = 'A pioneering family-owned winery established in 1974, Capel Vale cultivates vineyards across three cool climate regions—Geographe, Margaret River, and Mount Barker—to craft wines with distinct regional character and elegant fruit profiles.' WHERE slug = 'capel-vale';
UPDATE venues SET description = 'Located in Ferguson Valley two hours south of Perth, this estate winery offers tastings of handcrafted red and white wines in a scenic setting of rolling hills. The cellar door is open daily for wine tastings and features a curated range of wines and giftware.' WHERE slug = 'willow-bridge';
UPDATE venues SET description = 'Independent Sunshine Coast brewery founded by brothers Lance and Craig, specialising in premium lagers brewed with uncompromising standards. The Noosaville taproom offers a refined coastal experience showcasing their core range including Japanese-style lagers.' WHERE slug = 'heads-of-noosa';
UPDATE venues SET description = 'Family-owned winery established in 1998 by Greek migrants Peter and Eleni Markeas. Produces Riesling, Shiraz and Cabernet Sauvignon with a Mediterranean influence, offering wine club membership and vineyard tours.' WHERE slug = 'mallee-estate';
UPDATE venues SET description = 'Award-winning cidery in Daylesford''s countryside with a daily cellar door and restaurant. Specialising in traditional ciders crafted from organically grown heritage apples, featuring a casual lunch menu and regular live music events. Dog and family-friendly.' WHERE slug = 'daylesford-cider';
UPDATE venues SET description = 'Family-operated winery and cidery in Wonga Park producing wines and craft ciders in-house. The cellar door offers tastings, platters, and a pet-friendly outdoor area, located just 45 minutes from Melbourne''s CBD.' WHERE slug = 'kellybrook';
UPDATE venues SET description = 'Geelong-based brewery specialising in barrel-aged craft beers. White Rabbit focuses on complex, aged brews that showcase the depth and character developed through extended barrel maturation.' WHERE slug = 'white-rabbit';
UPDATE venues SET description = 'Urban winery in Melbourne''s Brunswick East making premium handcrafted wines from Victorian grapes. Functions as a winery, wine bar, bottle shop and events space offering tastings, experiences and venue hire in a relaxed, inclusive atmosphere.' WHERE slug = 'noisy-ritual';
UPDATE venues SET description = 'Family-owned winery established in 1996 near Bendigo, producing handcrafted premium red wines using organic principles and traditional minimal-intervention techniques. Specialises in Shiraz and Tempranillo with cellar door sales and online ordering available.' WHERE slug = 'pondalowie';
UPDATE venues SET description = 'Australia''s oldest registered distillery since 1884, Beenleigh crafts rum from local molasses and rainwater using copper pot distillation. The riverside location offers tours, tastings, a restaurant, and cocktail experiences showcasing over 140 years of rum-making heritage.' WHERE slug = 'beenleigh-artisan';
UPDATE venues SET description = 'Located in Fyshwick, this brewery operates a taproom serving freshly poured beers brewed with a focus on sustainability. The venue offers brewery tours and event hosting options including weddings.' WHERE slug = 'pact-beer';
UPDATE venues SET description = 'Family-owned winery in Wallaroo''s Hills of Hall sub-district offering weekend cellar door tastings, a bistro with seasonal menus, vineyard views, and on-site accommodation in a converted historic property.' WHERE slug = 'surveyors-hill';
UPDATE venues SET description = 'Established in 1996 on volcanic soils in Broke, this family-owned winery produces single-vineyard, sustainably farmed wines alongside an award-winning restaurant serving hyper-seasonal produce grown on-site.' WHERE slug = 'andrew-margan';
UPDATE venues SET description = 'Family-owned artisanal distillery in the Mornington Peninsula specialising in small-batch gin, brandy and liqueurs made with local native botanicals. Offers gin masterclasses, brandy tastings and immersive experiences including farm-to-table cocktail workshops.' WHERE slug = 'bass-flinders-moonshine';
UPDATE venues SET description = 'Nestled in the World Heritage Blue Mountains, this cidery produces craft ciders from freshly crushed apples with no added sugar and gluten-free options. The cellar door offers dining, live music, farm grounds and accommodation for a full visitor experience.' WHERE slug = 'bilpin-cider';
UPDATE venues SET description = 'Award-winning Hunter Valley winery set high in the region, crafting exceptional Semillon, Chardonnay, and Shiraz since 1968. Features cellar door tastings, restaurant and pizzeria, accommodation, and hosts events with scenic vineyard views.' WHERE slug = 'bimbadgen';
UPDATE venues SET description = 'Pioneering cool-climate winery established in Orange in 1983, producing quality wines from gravelly vineyard blocks suited to varieties like Riesling, Cabernet Franc and Shiraz. Features a cellar door for tastings and visits.' WHERE slug = 'bloodwood-wines';
UPDATE venues SET description = 'Award-winning brewery and restaurant housed in a restored 1900s heritage building in Katoomba, serving craft beers and local produce. Located two minutes from Katoomba Station with onsite parking and a deck for dining.' WHERE slug = 'blue-mountains-brewery';
UPDATE venues SET description = 'Award-winning craft gin and vodka distillery in Katoomba featuring The Factory Bar with house-distilled spirits, locally sourced beverages, live weekend music, and distillery tours available.' WHERE slug = 'blue-mountains-distillery';
UPDATE venues SET description = 'Family-run nanobrewery in Marrickville producing an ever-changing selection of small batch beers with a focus on quality ingredients and creative hop-forward styles. Open for tastings and events at their taproom.' WHERE slug = 'bracket-brewing';
UPDATE venues SET description = 'Marrickville brewery and bottle shop featuring rotating taps and collaborative brews. Offers same-day delivery and online ordering alongside an in-store bar experience, with extended daily hours until 9:45 pm.' WHERE slug = 'bucket-boys';
UPDATE venues SET description = 'Family-owned winery offering wine and beer tastings at the cellar door, plus on-site accommodation in two cottages. Known for hosting regular live music and pizza events, and available for private functions and celebrations.' WHERE slug = 'burnbrae-wines';
UPDATE venues SET description = 'Established in 1945, this family-owned Griffith winery produces a range of wines including the premium Three Bridges collection. Visitors can explore the cellar door experience at the Riverina headquarters or the Barossa Valley tasting room.' WHERE slug = 'calabria-wines';
UPDATE venues SET description = 'One of Australia''s largest family-owned winemakers, Casella produces the world''s leading Australian wine brand Yellow Tail alongside premium wines and craft beverages including beer, cider and spirits from their Yenda base in the Riverina region.' WHERE slug = 'casella-family';
UPDATE venues SET description = 'Located on Lake George near Canberra, this winery features a café-cellar door and museum. The venue produces sparkling, rosé, white and red wines, along with gin, available for tasting and purchase.' WHERE slug = 'collector-wines';
UPDATE venues SET description = 'Specialising in premium, single vineyard wines from Orange''s cool, high-altitude region, this cellar door produces hand-crafted small batches including Pinot Noir, Chardonnay, Riesling and traditional method sparkling wines. Tastings available by appointment.' WHERE slug = 'colmar-estate';
UPDATE venues SET description = 'Established in 1822 and family-owned since 1947, this award-winning Shoalhaven winery offers cellar door tastings of estate-grown wines with Pacific Ocean views, plus heritage-listed accommodation nestled among rolling vineyards at the foothills of Mt. Coolangatta.' WHERE slug = 'coolangatta-estate';
UPDATE venues SET description = 'Located in the Snowy Mountains foothills near Tumbarumba, this cellar door and restaurant showcases cold-climate wines including sparkling wines and Pinot Noir. The venue offers private vineyard tours, picnic baskets, and hosts weddings and events.' WHERE slug = 'courabyra-wines';
UPDATE venues SET description = 'I cannot provide an accurate description for Cowra Estate winery based on the website content provided. The website appears to be for a real estate agency, not a winery, and contains no information about wine production, vineyard characteristics, or visitor experiences at Cowra Estate.

To write a factual description following the guidelines, I would need access to the actual winery''s website or verified information about their operations.' WHERE slug = 'cowra-estate';
UPDATE venues SET description = 'Family-run winery on the NSW South Coast offering cool climate wines, farm-to-table dining, and luxury accommodation with views over Burrill Lake and the Budawang Ranges.' WHERE slug = 'cupitts-estate';
UPDATE venues SET description = 'Award-winning winery located on Rocky Waterhole Road in Mudgee, producing boutique wines. The estate previously offered cellar door experiences but is now permanently closed, with online sales available until June 28th.' WHERE slug = 'moothi-estate';
UPDATE venues SET description = 'Award-winning family-run brewery in Brookvale producing hop-forward ales and IPAs alongside fruit-forward lagers. The venue features a beer garden and tap room where visitors can sample core range beers and seasonal releases while booking a table to enjoy the space.' WHERE slug = 'dad-daves-brewing';
UPDATE venues SET description = 'Family-owned Hunter Valley winery producing handcrafted small-batch wines, from iconic Hunter classics like Semillon and Shiraz to innovative alternate varieties. James Halliday 5 red star rated.' WHERE slug = 'de-iuliis-wines';
UPDATE venues SET description = 'Award-winning cool climate winery in the Canberra District producing distinctive reds, whites and more. The cellar door in Murrumbateman showcases Eden Road''s vineyard terroir through their portfolio, with a wine club offering exclusive selections and events.' WHERE slug = 'eden-road-wines';
