-- SBA Description Updates — 2026-03-16 01:17
-- 72 venues updated, 28 skipped

UPDATE venues SET description = 'Located in the historic gold rush town of Beechworth, this brewery produces a diverse range of craft beers including pale ales, IPAs, hazy pales, and alcohol-free options. The venue offers tastings and events, with a beer club providing members exclusive access to their latest releases.' WHERE slug = 'beechworth-brewing';
UPDATE venues SET description = 'An iconic winery in Coonawarra''s terra rossa heartland, Parker Estate specializes in world-class Cabernet Sauvignon crafted from its 16-hectare Abbey vineyard. The cellar door, housed in a distinctive limestone building, offers tastings guided by experienced winemakers.' WHERE slug = 'parker-coonawarra';
UPDATE venues SET description = 'Award-winning craft brewery in Burswood with an on-site taproom and gastrobrewery serving innovative beers alongside gourmet food including burgers and seafood.' WHERE slug = 'blasta-brewing';
UPDATE venues SET description = 'An independent micro-brewery operating since 2005, Indian Ocean Brewing Co crafts award-winning beers and small batch specialties alongside an extensive grill menu and pizzas. Located at The Marina in Mindarie with stunning ocean views, it offers a destination experience combining quality handcrafted brews with waterfront dining.' WHERE slug = 'indian-ocean-brewing';
UPDATE venues SET description = 'Secluded Margaret River vineyard nestled in jarrah forest, offering cellar door tastings, accommodation in spa chalets, and wines showcasing regional terroir crafted through dedicated viticultural practices.' WHERE slug = 'brookland-valley';
UPDATE venues SET description = 'Brewing authentic Czech Pilsner in Brunswick since 2016, Foreigner Brewing collaborates with Czech master brewers and rotates innovative ales alongside their flagship Silent Hunter. The intimate warehouse brewery fosters a strong community atmosphere with games, dog-friendly vibes, and brewers regularly chatting behind the bar.' WHERE slug = 'foreigner-brewing';
UPDATE venues SET description = 'Independent Melbourne craft brewery operating a production facility and taproom in Reservoir, offering a rotating range of house-brewed beers alongside merchandise and a rewards program for regulars.' WHERE slug = 'hawkers-reservoir';
UPDATE venues SET description = 'This Melbourne brewery is part of the Rocky Ridge family, known for their West Coast IPAs and innovative collabs like Good Energy. They offer core beers, limited releases, and barrel series across multiple locations.' WHERE slug = 'rocks-brewing-melb';
UPDATE venues SET description = 'Housed in The Cannery precinct, this French-inspired brewpub pairs house-made beers, cocktails and spritzes with produce-driven seasonal cuisine. Brewery Director Vince crafts award-winning beverages that showcase fresh, local ingredients, while Head Chef Thomas sources from local farmers and providores to create approachable dishes rooted in French culinary philosophy.' WHERE slug = 'frenchies-brewery';
UPDATE venues SET description = 'Australia''s first cooperative brewery, where members own shares and have a democratic say in operations. Hopsters brews craft beers like Griffo XPA and Pale Ale while fostering community through tastings, brew days, and homebrew competitions.' WHERE slug = 'hopsters-brewing';
UPDATE venues SET description = 'Situated in a renovated church in Pokolbin''s heart, this boutique winery pairs contemporary Hunter Valley wines with a premium salumi and cheese experience. Known for thought-provoking wines that blur traditional and contemporary styles, Usher Tinkler grows all fruit for production.' WHERE slug = 'usher-tinkler';
UPDATE venues SET description = 'Small-scale brewery in Forrest producing preservative-free, vegan-friendly beers brewed entirely on-site using pure Otways water and local hops. The renovated general store venue offers dining, live music, and views of the 600-litre brewhouse.' WHERE slug = 'forrest-brewing';
UPDATE venues SET description = 'East Perth brewery and kitchen serving fresh craft beers direct from the tank. The venue features an on-tap selection, full food menu, and hosts events and functions in a space designed around bold flavors and vibrant community atmosphere.' WHERE slug = 'bright-tank-brewing';
UPDATE venues SET description = 'Founded in 1992, this iconic Margaret River winery offers sweeping views of the Five Ashes vineyard and surrounding valleys from its cellar door restaurant. Open daily for lunch with seasonal local menus, the venue also hosts winery tours and tastings.' WHERE slug = 'hamelin-bay';
UPDATE venues SET description = 'Biodynamic Margaret River winery offering guided tastings of single-vineyard wines with minimal intervention winemaking. The cellar door provides a relaxed setting where visitors can enjoy wines paired with seasonal fare from the Vintner''s Kitchen, open daily.' WHERE slug = 'mchenry-hohnen';
UPDATE venues SET description = 'Located at 68 Chambers Road in Hay Valley, this Adelaide Hills brewery welcomes visitors to enjoy craft beverages amid scenic surroundings. The venue offers long lunch bookings and brewery tours at their main location, LOT.100.' WHERE slug = 'mismatch-hills';
UPDATE venues SET description = 'Located at 168 Olivers Road in McLaren Vale, Swell Brewing Co operates a brewery and taphouse open daily for food and drinks. The venue produces a range of craft beers including hazy IPAs, kettle sours, and hop water, available to enjoy on-site or order online.' WHERE slug = 'swell-brewing';
UPDATE venues SET description = 'Specialising in emerging Italian and Spanish varieties alongside heritage Shiraz from 70-year-old vines, this single-estate Granite Belt winery offers intimate tastings led by the owner in a beautiful cellar door setting.' WHERE slug = 'savina-lane';
UPDATE venues SET description = 'Award-winning Brisbane brewery offering hop-forward craft beers and modern Australian cuisine across two venues in Yeerongpilly and Birtinya, with a focus on celebrating traditional and contemporary beer styles.' WHERE slug = 'slipstream-brewing';
UPDATE venues SET description = 'Salisbury-based brewery crafting big-flavour beers across ales, lagers, stouts and sours, including experimental wild and barrel-aged offerings through their Bunker range. Open Thursday to Sunday with taproom venues in Salisbury and Springfield.' WHERE slug = 'ballistic-beer';
UPDATE venues SET description = 'Located in Woolloongabba, this Brisbane brewery and kitchen produces craft beers and offers a space to enjoy them on-site. Good Land Brewing Co focuses on small-batch brewing, with regular new releases available for visitors.' WHERE slug = 'good-land-brewing';
UPDATE venues SET description = 'Established in 1955 by Czech vigneron Paul Osicka, this Heathcote institution remains the region''s longest-standing producer. Now in its third generation under Simon Osicka, the winery crafts small-batch estate wines from mature, unirrigated vines using minimal synthetic chemicals and meticulous hand-tending.' WHERE slug = 'paul-osicka';
UPDATE venues SET description = 'Six-generation Rutherglen winery producing estate wines from dry-grown vineyards since 1860, featuring a restaurant helmed by classically-trained chef Briony Bradford and showcasing local ingredients alongside Durif, Shiraz, Muscat and natural winemaking experiments.' WHERE slug = 'jones-winery-rutherglen';
UPDATE venues SET description = 'Award-winning single-estate winery in Tynong North offering cool-climate Gippsland wines inspired by Bordeaux and Burgundy, paired with Modern-Australian cuisine at the on-site restaurant using local produce and kitchen garden ingredients.' WHERE slug = 'cannibal-creek';
UPDATE venues SET description = 'Wild ale and sour specialist sharing Village, a joint taproom with Mountain Culture Beer Co in Marrickville. Located near Newtown station alongside independent venues including The Factory Theatre and specialty coffee, the brewery offers a curated menu designed for sharing.' WHERE slug = 'wildflower-brewing';
UPDATE venues SET description = 'Family-owned winery with 5-star Halliday rating, producing wines from Margaret River and Great Southern regions. Features the Wine Chapel, an architecturally striking tasting venue set amongst native forest with valley views, offering curated tastings and locally sourced pairings.' WHERE slug = 'howard-park';
UPDATE venues SET description = 'Historic 186-hectare vineyard in Clarendon''s elevated hills, first planted in 1971 and bottled under its own label since 2012. Now farmed organically and biodynamically, Hickinbotham produces distinctive Shiraz and Cabernet under winemakers Christopher Carpenter and Peter Fraser.' WHERE slug = 'hickinbotham-clarendon';
UPDATE venues SET description = 'Founded in 2004 by Master Distiller Cameron Syme, this Albany distillery produces premium craft spirits including Limeburners single malt whisky, Giniversity gin, and Tiger Snake whiskey. Visitors can enjoy distillery tours and gin blending classes.' WHERE slug = 'great-southern-distilling';
UPDATE venues SET description = 'A rustic Swan Valley distillery featuring hand-crafted spirits paired with innovative West Australian cuisine using native ingredients and local produce. The venue emphasizes minimal waste and sustainability while offering non-alcoholic options and smaller pours for all visitors.' WHERE slug = 'old-youngs';
UPDATE venues SET description = 'Celebrated Barossa Valley producer known for premium single-vineyard Shiraz expressions, particularly the flagship Roennfeldt Road range. Offers cellar door tastings and direct online sales with national shipping.' WHERE slug = 'greenock-creek';
UPDATE venues SET description = 'Tanunda-based winery producing distinctive single vineyard and single barrel expressions, with particular focus on Shiraz, Grenache, and Mataro. Cellar door tastings available through the Artisans of Barossa collective experience.' WHERE slug = 'schwarz-wine';
UPDATE venues SET description = 'Highly focused Barossa producer specialising in small-batch Shiraz from premium vineyard sites across the region, including their flagship The Standish. Tastings by appointment.' WHERE slug = 'standish-wine';
UPDATE venues SET description = 'Located in Murrumbateman, Shaw Vineyard Estate offers award-winning cool climate wines and seated tasting experiences overlooking the Southern Tablelands. The estate features a cellar door, restaurant, and versatile event spaces.' WHERE slug = 'shaw-vineyard';
UPDATE venues SET description = 'Perched above 900 metres in New England''s Macintyre Valley, this family-owned winery specializes in small-batch, estate-grown wines including rare varietals like Tempranillo Blanc. The cellar door offers panoramic views over state forest and volcanic basalt soils that define the region''s distinctive cool-climate expressions.' WHERE slug = 'toppers-mountain';
UPDATE venues SET description = 'Nestled in the Huon Valley south of Hobart, this award-winning winery produces premium Pinot Noir and other varietals alongside fine dining. The cellar door and restaurant offer mountain and vineyard views in a peaceful country setting.' WHERE slug = 'home-hill';
UPDATE venues SET description = 'Sixth-generation biodynamic winery in Tasmania''s Derwent Valley producing minimal-intervention Pinot Noir, Chardonnay and sparkling wines. Cellar door tastings available.' WHERE slug = 'stefano-lubiana';
UPDATE venues SET description = 'Established family winery on the Mornington Peninsula offering estate-grown wines at the cellar door, paired with Asian fusion dining. Seated tastings available Thursday to Sunday in a setting of sprawling vines and gardens.' WHERE slug = 'stumpy-gully';
UPDATE venues SET description = 'A pioneering family-owned winery established in 1974, Capel Vale cultivates vineyards across three cool-climate regions—Geographe, Margaret River, and Mount Barker—crafting wines with distinct regional character and elegant fruit profiles at their Cellar Door in Capel.' WHERE slug = 'capel-vale';
UPDATE venues SET description = 'Located two hours south of Perth in Ferguson Valley''s rolling hills, this estate produces handcrafted wines from vineyard to bottle. The cellar door offers tastings of their red and white range, open daily with friendly staff guiding visitors through the experience.' WHERE slug = 'willow-bridge';
UPDATE venues SET description = 'Independently owned Noosa brewery founded by brothers Lance and Craig, specializing in premium lagers brewed with uncompromising standards. The taproom offers a refined coastal experience showcasing their core range including Japanese Style Lager and seasonal offerings.' WHERE slug = 'heads-of-noosa';
UPDATE venues SET description = 'A family-owned Riverland winery founded by Peter and Eleni Markeas, Greek migrants who realised their vineyard dream after 30 years of development. The estate produces quality Australian wines including Cabernet Sauvignon, Shiraz, and Riesling, offering a taste of Mediterranean warmth and taverna atmosphere.' WHERE slug = 'mallee-estate';
UPDATE venues SET description = 'Based on the website content provided, I can only confirm the venue exists and has an age-gated website. However, I cannot verify specific details about their barrel-aging specialty, brewing style, or what makes them worth visiting from this content alone.

Here''s a description using only confirmed information:

White Rabbit Brewery is a Geelong-based craft brewery specializing in barrel-aged beers. The brewery maintains a professional online presence with age verification measures in place.

However, I''d recommend providing additional website content (such as their about page, product listings, or venue description) to write a more compelling and detailed description that better serves the Small Batch Atlas directory.' WHERE slug = 'white-rabbit';
UPDATE venues SET description = 'An urban winery in Melbourne''s Brunswick East making premium wines from Victorian grapes, operating as a wine bar and bottle shop by day and events space by night. Known for its relaxed, inclusive approach to winemaking and immersive experiences ranging from tastings to full membership programs.' WHERE slug = 'noisy-ritual';
UPDATE venues SET description = 'Family-owned winery established in 1996 near Bendigo, specialising in handcrafted red wines using traditional techniques and minimal intervention. Known for premium Shiraz and Tempranillo from organically farmed vineyards, with cellar door and online ordering available.' WHERE slug = 'pondalowie';
UPDATE venues SET description = 'Australia''s oldest registered distillery since 1884, Beenleigh Artisan Distillers crafts rum from local sugarcane molasses using traditional copper pot distillation on the Albert River. Visitors can tour the historic riverside location, taste spirits, dine at the on-site restaurant, and experience the distillery''s 140-year heritage.' WHERE slug = 'beenleigh-artisan';
UPDATE venues SET description = 'Located in Fyshwick, this brewery operates a taproom serving freshly poured beers alongside a rotating selection of house brews. The venue offers brewery tours and event hosting, positioning itself as a community gathering space for craft beer enthusiasts.' WHERE slug = 'pact-beer';
UPDATE venues SET description = 'Family-owned winery in the scenic Hills of Hall sub-district offering cellar door tastings, weekend bistro lunches, and vineyard views. Includes accommodation and venue hire on a 100-acre property near Canberra.' WHERE slug = 'surveyors-hill';
UPDATE venues SET description = 'Family-owned winery established in 1996 on volcanic soils in Broke, producing single-vineyard wines using sustainable farming practices. The award-winning cellar door and on-site restaurant showcase seasonal produce grown and reared on the estate.' WHERE slug = 'andrew-margan';
UPDATE venues SET description = 'Family-owned artisanal distillery in the Mornington Peninsula specialising in small-batch gin, brandy and innovative spirits using local native botanicals. Offers gin masterclasses, brandy tastings and immersive experiences including farm-to-table cocktail masterclasses.' WHERE slug = 'bass-flinders-moonshine';
UPDATE venues SET description = 'Nestled in the World Heritage Blue Mountains, this cidery crafts small-batch ciders from freshly crushed apples with no added sugar. The cellar door offers dining, live music, farm grounds, and accommodation for a full visitor experience.' WHERE slug = 'bilpin-cider';
UPDATE venues SET description = 'Marrickville brewery and bottle shop featuring rotating taps, collaborative brews, and a curated selection of beer and cider. Offers same-day delivery and online ordering through Thirstville.' WHERE slug = 'bucket-boys';
UPDATE venues SET description = 'Established in 1945, this family-owned Griffith winery produces a diverse range of wines including their premium Three Bridges collection. The venue offers tastings at their Riverina headquarters and a secondary tasting room in the Barossa Valley.' WHERE slug = 'calabria-wines';
UPDATE venues SET description = 'Australia''s largest wine producer and home to the globally renowned Yellow Tail brand, Casella Family Brands operates from its Yenda base with a diverse portfolio spanning wines, spirits, beer and cider crafted for international markets.' WHERE slug = 'casella-family';
UPDATE venues SET description = 'I cannot write an accurate description for this venue based on the provided information. The website content appears to be from a real estate agency rather than the winery itself, and contains no details about Cowra Estate''s wines, facilities, or visitor experience beyond the current description. I would need access to the actual winery''s website or verified information to write a factual description.' WHERE slug = 'cowra-estate';
UPDATE venues SET description = 'Located in Wollongong, this brewery combines craft beer production with a full bar and bistro. Open Tuesday to Sunday with kitchen service for lunch and dinner, it offers a venue for casual visits, functions, and events.' WHERE slug = 'illawarra-brewing';
UPDATE venues SET description = 'Award-winning craft brewery nestled amongst wine tanks in the Hunter Valley, brewing preservative-free beers on-site since 2017. Their rotating range includes signature lagers, IPAs, pale ales and stouts, with many medal-winning brews available exclusively at the venue.' WHERE slug = 'ironbark-hill';
UPDATE venues SET description = 'Laid-back South Coast brewery near Huskisson creating craft beers focused on sustainability. The taproom offers a range of IPAs and seasonal releases, with a Hoptimist membership program providing regular perks for beer enthusiasts.' WHERE slug = 'jervis-bay-brewing';
UPDATE venues SET description = 'Certified organic and biodynamic producer on 150 acres in the Hunter Valley''s Broke Fordwich region, offering minimal-intervention wines and sustainable farmstay accommodation with views of the Brokenback mountain range.' WHERE slug = 'krinklewood';
UPDATE venues SET description = 'Lyre''s Spirit Co offers a curated collection of non-alcoholic spirit alternatives including gin, rum, tequila, bourbon and vermouth, alongside premixed cocktails and sparkling wine. The range enables craft cocktail creation at home with recipe inspiration and cocktail sets available.' WHERE slug = 'lyres-spirit';
UPDATE venues SET description = 'Brookvale distillery producing gin, vodka, whisky and liqueurs using coastal botanicals. The venue offers hands-on gin school experiences, distillery tours and a bar open Thursday to Sunday, with a cellar door operating daily.' WHERE slug = 'manly-spirits';
UPDATE venues SET description = 'Family-owned Hunter Valley winery established in 1996, producing single vineyard wines from sustainably farmed volcanic soils. Features a rammed earth cellar door, award-winning restaurant serving hyper-seasonal produce, and accommodation in the Broke foothills.' WHERE slug = 'margan-wines';
UPDATE venues SET description = 'Family-owned Hunter Valley winery specializing in individual vineyard Semillon, Chardonnay and Shiraz, with winemaker Rhys Eather bringing French and Italian expertise to classic Hunter Valley wines.' WHERE slug = 'meerea-park';
UPDATE venues SET description = 'Housed in a restored 1900s heritage building, this Katoomba brewpub serves award-winning hazy IPAs and stouts alongside locally-sourced food on a scenic deck. Voted NSW''s best brewery venue in 2023, it''s a two-minute walk from the train station.' WHERE slug = 'mountain-culture-beer';
UPDATE venues SET description = 'A vibrant craft brewery nestled in Port Stephens, part of the B.Farm estate that combines brewing, distillery, restaurants, and accommodation. Known for beers including Whale Ale and Angry Man Pale Ale, set within a destination offering immersive experiences and fine food.' WHERE slug = 'murrays-brewing';
UPDATE venues SET description = 'A vibrant estate brewery and restaurant in Port Stephens offering Murray''s Craft Brewing Co beers, B. Farm wines, and artisanal spirits alongside dining and accommodation experiences in a scenic coastal location.' WHERE slug = 'murrays-port-stephens';
UPDATE venues SET description = 'Located in Marrickville on the Inner West Ale Trail, this independent brewery and taproom offers a diverse range of flavoursome drinks including core beers, limited edition releases, and craft cocktails, with a relaxed beer garden atmosphere.' WHERE slug = 'sauce-brewing';
UPDATE venues SET description = 'Independently owned Central Coast brewery in Erina producing full-flavoured craft beers onsite. The taproom at The Sawmill features 16 taps, a dog-friendly outdoor area, and a restaurant with wine and cocktail options.' WHERE slug = 'six-string-brewing';
UPDATE venues SET description = 'Specialist cool-climate producer of Chardonnay, Pinot Noir and Pinot Gris, set in an architecturally striking limestone building with cellar door tastings, dining room and on-site accommodation overlooking the Mornington Peninsula.' WHERE slug = 'kooyong-estate';
UPDATE venues SET description = 'Home to a 31-tank brewery, tasting room, and canteen set in leafy surrounds, this is Stone & Wood''s flagship Byron Bay location and birthplace of Pacific Ale. The venue offers visitors the chance to experience the brewery''s core range and limited releases in an on-site setting.' WHERE slug = 'stone-wood-byron-bay';
UPDATE venues SET description = 'A family-owned farm distillery in Bathurst producing award-winning gin and whisky using locally-sourced ingredients and sustainable practices. Visitors can experience the distillery set on The Grange property, where botanicals like hand-picked rose petals and native Australian botanicals are distilled into distinctive spirits.' WHERE slug = 'stone-pine-distillery';
UPDATE venues SET description = 'Family-owned winery overlooking Mount Canobolas, specialising in cool-climate wines including award-winning Chardonnay and Pinot Noir. The cellar door offers guided tastings and curated food and wine pairing experiences with an in-house chef and sommelier team.' WHERE slug = 'swinging-bridge-wines';
UPDATE venues SET description = 'Located on Albion Street in Surry Hills near Central Station, this brewpub produces award-winning small batch lagers and ales in an industrial warehouse setting with exposed brick and street art. Visitors can watch brewers at work while enjoying pub food, live music, and sampling specialty beers.' WHERE slug = 'sydney-brewery';
